### ISSUE TITLE
Xenforo media embeds relying on github.io no longer work

### ISSUE THREAD

**Issue by jeevesmkii** [s9e/s9e.github.io#2]
github.io is now serving responses containing the X-Frame-Options: Deny header, rendering all the plugins that rely on pages served from s9e.github.io non-functional..

**Comment by JoshyPHP** [comment]
Yes. As far as XenForo is concerned, I posted an update that uses a different host. s9e/XenForoMediaBBCodes@b58e8697c394c6ec30bc407299c5e4c5d6e2e970 I'm still looking for info about that change, as I only became aware of it today.

**Comment by JoshyPHP** [comment]
The `X-Frame-Options` header has been removed.
