### ISSUE TITLE
threads,net not working

### ISSUE THREAD

**Issue by jadedgnome** [s9e/s9e.github.io#4]
https://github.com/s9e/s9e.github.io/blob/master/iframe/2/threads.min.html
https://raw.githubusercontent.com/s9e/s9e.github.io/master/iframe/2/threads.min.html

`src='+a+'/embed/>`

https://s9e.github.io/iframe/2/threads.min.html#C0zXcQmxO77

the above url resolves to this url https://www.threads.net/t/C0zXcQmxO77/embed/ but it doesn't work.

https://www.threads.net/t/C0zXcQmxO77/  works so i think the /embed that threads.min.html is adding to the url is messing up the embed.

**Comment by JoshyPHP** [comment]
As far as I can tell, the page works fine, even when accessed directly via the link in your example, https://s9e.github.io/iframe/2/threads.min.html#C0zXcQmxO77

Try again with a fresh empty browser profile. It's possible that a privacy extension is blocking the embed.
